version: '3.4'
name: masstransitpoc-compose
services:

  masstransitpoc.rabbitmq:
    image: ${DOCKER_REGISTRY-}masstransit/rabbitmq
    container_name: rabbitmq
    hostname: local-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
      - rabbitmq-data:/var/lib/rabbitmq

  masstransitpoc.consumer:
    image: ${DOCKER_REGISTRY-}masstransitpocconsumer
    build:
      context: .
      dockerfile: MassTransitPoc.Consumer/Dockerfile
    volumes:
      - shared-data:/app/shared-data
    depends_on:
      - masstransitpoc.rabbitmq
 
  masstransitpoc.consumer2:
    image: ${DOCKER_REGISTRY-}masstransitpocconsumer
    build:
      context: .
      dockerfile: MassTransitPoc.Consumer/Dockerfile
    volumes:
      - shared-data:/app/shared-data
    depends_on:
      - masstransitpoc.rabbitmq

  masstransitpoc.api:
    image: ${DOCKER_REGISTRY-}masstransitpocapi
    build:
      context: .
      dockerfile: MassTransitPoc.Api/Dockerfile
    volumes:
      - shared-data:/app/shared-data
    depends_on:
      - masstransitpoc.rabbitmq

volumes:
  shared-data:
  rabbitmq-data:
